name = input ("What is your name? ")
favorite_animal = input ("What is your favorite animal? ")
question_1 = input ("What noise does the animal make? ")
question_2 = input ("What colors is the animal? ")
question_3 = input ("Why is it your favorite animal? ")
question_4 = input ("Where does your animal live? ")
print ((name + "s favorite animal is a ") + favorite_animal + (". The animal makes the noise ") + question_1 )
print ("The animal is the color(s) " + question_2 + ". " + name + (" Likes the animal because ") + question_3)
print ("The areas the animal lives include " + question_4)