print("Space shuttle supply check")
countdown = input("Seconds until launch: ")
oxygen_tanks = input("Oxygen tanks: ")
food_packs = input("Food packs: ")
water_packs = input("Water packs: ")
print("Total supplies")
print ("Seconds until launch: "+countdown)
print ("o2 tanks: "+oxygen_tanks)
print ("Food packs: "+food_packs)
print ("Water packs: "+water_packs)
oxygen_tanks = input("Please confirm oxygen tanks:")
print("Confirmed supplies")
print ("Seconds until launch: "+countdown)
print ("o2 tanks: "+oxygen_tanks)
print ("Food packs: "+food_packs)
print ("Water packs: "+water_packs)